[tool.poetry]
name = "fastapi-ca"
version = "0.1.0"
description = ""
authors = ["dexter <dexter.haan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.103.2"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
py-ulid = "^1.0.3"
sqlalchemy = "^2.0.23"
mysqlclient = "^2.2.0"
alembic = "^1.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
